Update for graphql-tools v6 & Products refactor
ThatConference/that-api-garage pull request #12
Opened 2020-12-18 22:29 UTC by brettski

Update for graphql-tools v6
Refactor products
where product type stores all details on that product record. Association not needed.
Product enum and _typeResolve logic centralized in that-api-schema

2020-12-18 23:05 UTC, csell5 commented on src/graphql/typeDefs/dataTypes/product/ticket.graphql
> +  eventId: ID
shouldn't this be required

2020-12-18 23:09 UTC, csell5 requested changes

2020-12-18 23:09 UTC, csell5 commented on src/graphql/typeDefs/dataTypes/product/ticket.graphql
> +  onSaleFrom: Date
shouldn't this be required

2020-12-18 23:09 UTC, csell5 commented on src/graphql/typeDefs/dataTypes/product/ticket.graphql
> +  "Reference to processor for associated product (Stripe, Shopify, etc.)"
shouldn't this be required

2020-12-18 23:09 UTC, csell5 commented on src/graphql/typeDefs/dataTypes/product/partnership.graphql
> +  eventId: ID
shouldn't this be required

2020-12-18 23:09 UTC, csell5 commented on src/graphql/typeDefs/dataTypes/interfaces/productBase.graphql
> +  eventId: ID
shouldn't this be required

2020-12-18 23:09 UTC, csell5 commented on src/graphql/typeDefs/dataTypes/interfaces/productBase.graphql
> +  onSaleFrom: Date
shouldn't this be required

2020-12-18 23:09 UTC, csell5 commented on src/graphql/typeDefs/dataTypes/interfaces/productBase.graphql
> +  processor: ProcessorRef
shouldn't this be required

2020-12-18 23:11 UTC, brettski commented on src/graphql/typeDefs/dataTypes/product/ticket.graphql
> +  eventId: ID
I don't know should it? Are you saying for the Ticket type only have it required since we will not sell a ticket which isn't associated with an event.

2020-12-18 23:12 UTC, brettski commented on src/graphql/typeDefs/dataTypes/product/ticket.graphql
> +  onSaleFrom: Date
maybe. When initially created you may not have dates set/available yet. That was my thought behind it.

2020-12-18 23:12 UTC, brettski commented on src/graphql/typeDefs/dataTypes/product/ticket.graphql
> +  "Reference to processor for associated product (Stripe, Shopify, etc.)"
maybe. When initially created you may not have dates set/available yet. That was my thought behind it.

2020-12-18 23:13 UTC, csell5 commented on src/graphql/typeDefs/dataTypes/product/ticket.graphql
> +  eventId: ID
look on base.

2020-12-18 23:14 UTC, brettski commented on src/graphql/typeDefs/dataTypes/product/partnership.graphql
> +  eventId: ID
I don't think so, will a partnership always be associated with an event? 
So now this has a smell to it where a partnership may before all events for a year, we have no way to represent that.

2020-12-18 23:14 UTC, brettski commented on src/graphql/typeDefs/dataTypes/interfaces/productBase.graphql
> +  eventId: ID
same answers as others

2020-12-18 23:14 UTC, brettski commented on src/graphql/typeDefs/dataTypes/interfaces/productBase.graphql
> +  onSaleFrom: Date
Same answer as others

2020-12-18 23:16 UTC, brettski commented on src/graphql/typeDefs/dataTypes/interfaces/productBase.graphql
> +  processor: ProcessorRef
Not required, especially on base. Maybe on the Types, e.g. ticket, if we decide that we should always be setting that value.

2020-12-19 00:45 UTC, csell5 approved these changes

2020-12-19 00:46 UTC, merged