WIP: Add product and product query
ThatConference/that-api-garage pull request #4
Opened 2020-11-19 01:57 UTC by brettski

some restructuring of the overall project

resolves #2

2020-11-20 21:48 UTC, brettski commented
All the pieces for products are there. probably needs a bit of clean up here and there.

2020-11-30 22:33 UTC, csell5 requested changes

2020-11-30 22:33 UTC, csell5 commented on package.json
>      "node": "14.x"
Are we really running 14 on the containers?

2020-11-30 22:33 UTC, csell5 commented on src/index.js
> +    enableMocking: false,
I take it we're using this elsewhere (that-api?)? if so, I'd set a better default there, and drop it here.

2020-11-30 22:33 UTC, csell5 commented on src/lib/__tests__/productDateForge.test.js
> +process.env.INFLUX_TOKEN = 'TEST_INFLUX_TOKEN_VALUE';
You should really set these up as part of the test setup/teardown such that it doesn't bleed into other testing and returns it back to what it was when it started.

2020-11-30 22:33 UTC, csell5 commented on src/graphql/typeDefs/mutations/productCreate.graphql
> +    @auth(requires: "adming")
role spelled wrong.

2020-11-30 23:04 UTC, brettski commented on package.json
>      "node": "14.x"
Nope, but it is the plan. Knock it back to 12 for now?

2020-11-30 23:04 UTC, brettski commented on src/index.js
> +    enableMocking: false,
Correct, Sentry is not used from the context so it was removed.

2020-11-30 23:19 UTC, csell5 commented on package.json
>      "node": "14.x"
I wasn't sure if the build/container was reading that to do what it does. if it's not, then I wouldn't worry about it.,

2020-11-30 23:20 UTC, csell5 commented on src/index.js
> +    enableMocking: false,
I actually wasn't talking about senty.. but rather the enable mocking.

2020-12-01 02:37 UTC, brettski commented on src/lib/__tests__/productDateForge.test.js
> +process.env.INFLUX_TOKEN = 'TEST_INFLUX_TOKEN_VALUE';
Added a afterAll() function to remove process vars.

2020-12-01 02:38 UTC, brettski commented on src/graphql/typeDefs/mutations/productCreate.graphql
> +    @auth(requires: "adming")
fixed. And yes I need to add create, update and get requests for partnership and membership which would have caught this.

2020-12-01 14:42 UTC, csell5 commented on src/lib/__tests__/productDateForge.test.js
> +process.env.INFLUX_TOKEN = 'TEST_INFLUX_TOKEN_VALUE';
but that assumes they wen't actually there before. I would do something like this

```
describe ...
 const OLD_ENV = process.env; // save for later

  beforeEach(() => {
    jest.resetModules() // clears the cache
    process.env = { ...OLD_ENV }; // makes a copy
   process.env.THING = 'THANG'; // sets the new stuff
  });

  afterAll(() => {
    process.env = OLD_ENV; // sets it back to what it was
  });
```

2020-12-01 14:46 UTC, brettski commented on src/lib/__tests__/productDateForge.test.js
> +process.env.INFLUX_TOKEN = 'TEST_INFLUX_TOKEN_VALUE';
Can't do that on before each as the are required for ` @thatconference/api` to load. I tried using a beforeAll(), but it complained that the variable wasn't a function when trying to run the tests.

2020-12-01 15:16 UTC, csell5 commented on src/lib/__tests__/productDateForge.test.js
> +process.env.INFLUX_TOKEN = 'TEST_INFLUX_TOKEN_VALUE';
I see.. this is why you're using require and doing it after the process.env is set.. that's some internal weirdness that would could easily get refactored by a change in prettier. I'd suggest. Pulling that require into the before all, then you can control all of that, including when it get's pulled in.

2020-12-01 17:24 UTC, csell5 approved these changes

2020-12-02 01:56 UTC, merged