Order Allocation allocate to member
ThatConference/that-api-garage pull request #41
Opened 2021-04-28 21:37 UTC by brettski

Refactor 'me' path for orders
add eventId filter for orders all query
allocate to logic in. doesn't check for current tickets

2021-05-03 22:39 UTC, csell5 requested changes

2021-05-03 22:39 UTC, csell5 commented on src/index.js
> +console.log('order allocation', orderAllocationEvents);
did you want to leave this in?

2021-05-03 22:39 UTC, csell5 commented on src/graphql/typeDefs/mutations/meOrderAllocation.graphql
> +  allocateTo(email: EmailAddress!): AllocateToResult!
no role required?

2021-05-03 22:39 UTC, csell5 commented on src/graphql/typeDefs/mutations/meOrder.graphql
> +  orderAllocation(orderAllocationId: ID!): MeOrderAllocationMutation
no role required?

2021-05-03 22:39 UTC, csell5 commented on src/graphql/typeDefs/mutations/orderAllocation.graphql
> +  allocateTo(member: AllocateToInput!): Boolean!
no role required?

2021-05-03 22:39 UTC, csell5 commented on src/graphql/typeDefs/mutations/orderAllocation.graphql
> +  setRefunded: Boolean!
no role required?

2021-05-03 22:39 UTC, csell5 commented on src/events/orderAllocation.js
> +      templateAlias: 'product-allocated-to-message',
don't forget to set this in production

2021-05-04 00:00 UTC, brettski commented on src/index.js
> +console.log('order allocation', orderAllocationEvents);
oops. removed.

2021-05-04 00:04 UTC, brettski commented on src/graphql/typeDefs/mutations/meOrder.graphql
> +  orderAllocation(orderAllocationId: ID!): MeOrderAllocationMutation
fixed, missed the whole path

2021-05-04 00:04 UTC, brettski commented on src/graphql/typeDefs/mutations/meOrderAllocation.graphql
> +  allocateTo(email: EmailAddress!): AllocateToResult!
fixed. missed the whole path

2021-05-04 00:05 UTC, brettski commented on src/graphql/typeDefs/mutations/orderAllocation.graphql
> +  allocateTo(member: AllocateToInput!): Boolean!
Not really, handled at the parent, though added for consistency.

2021-05-04 00:07 UTC, brettski commented on src/events/orderAllocation.js
> +      templateAlias: 'product-allocated-to-message',
There is no message to put up yet. I purposely didn't create a placeholder so we don't end up with a coonference

2021-05-04 00:12 UTC, brettski commented
Corrections pushed in 6ec4ef7

2021-05-04 13:10 UTC, csell5 approved these changes

2021-05-04 13:12 UTC, merged